import { template } from "es-toolkit/compat"
import { DeriveBanner, DeriveBannerData } from "@/types"

const DEFAULT_TEMPLATE = `@generated
本文件由 <%= formatAuthors(data.author) %> 自动生成，请勿手动修改。
This file is automatically generated by <%= formatAuthors(data.author) %>. DO NOT EDIT BY HAND.
<% const sourceText = formatSources(data.source) %><% if (sourceText) { %>
如需修改，请修改源文件：<%= sourceText %>
To make changes, please edit the source file: <%= sourceText %>
<% } %><% const overviewText = formatOverview(data.overview) %><% if (overviewText) { %>

@fileoverview
<%= overviewText %>
<% } %>`

function toTextArray(value: unknown): string[] {
  const arr = Array.isArray(value) ? value : [value]
  return arr
    .filter(v => typeof v === 'string' && v)
    .map(v => String(v).trim())
    .filter(Boolean)
}

function renderOverviewLines(node: DeriveBannerData['overview'] | undefined, depth = 0): string[] {
  if (node == null) return []
  const indent = '  '.repeat(Math.max(depth - 1, 0))
  const prefix = depth === 0 ? '' : '- '
  if (typeof node === 'string') {
    const text = node.trim()
    return text ? [`${indent}${prefix}${text}`] : []
  }
  const lines: string[] = []
  if (node.description && String(node.description).trim()) {
    lines.push(`${indent}${prefix}${String(node.description).trim()}`)
  }
  for (const child of node.items || []) {
    lines.push(...renderOverviewLines(child, depth + 1))
  }
  return lines
}

export function getBannerFormatter({
  formatter, 
  template: str
}: Pick<Exclude<DeriveBanner, false>, 'formatter' | 'template'>): NonNullable<Exclude<DeriveBanner, false>['formatter']> {
  if (typeof formatter === 'function') return formatter
  if (typeof str === 'string') return context => template(str)({ data: context.data })
  return context => {
    if (!Object.keys(context.data).length) return ''
    if (toTextArray((context.data as any)?.author).length === 0) return ''
    return template(DEFAULT_TEMPLATE, {
      imports: {
        formatAuthors: (author: any) => toTextArray(author).join(', '),
        formatSources: (source: any) => toTextArray(source).join('; '),
        formatOverview: (overview: DeriveBannerData['overview']) => renderOverviewLines(overview).join('\n')
      }
    })({ data: context.data })
  }
}