import type { DeriveBanner, DeriveBannerData, DeriveBannerContext, DeriveBannerStyle } from '../types.js'
import { template } from 'es-toolkit/compat'

const DEFAULT_STYLE: DeriveBannerStyle = 'block-jsdoc'
const DEFAULT_TEMPLATE = `@generated
本文件由 <%= formatAuthors(data.author) %> 自动生成，请勿手动修改。
This file is automatically generated by <%= formatAuthors(data.author) %>. DO NOT EDIT BY HAND.
<% const sourceText = formatSources(data.source) %><% if (sourceText) { %>
如需修改，请修改源文件：<%= sourceText %>
To make changes, please edit the source file: <%= sourceText %>
<% } %><% const overviewText = formatOverview(data.overview) %><% if (overviewText) { %>

@fileoverview
<%= overviewText %>
<% } %>`

function toTextArray(value: unknown): string[] {
  if (value == null) return []
  const arr = Array.isArray(value) ? value : [value]
  return arr
    .map(v => String(v).trim())
    .filter(Boolean)
}

function renderOverviewLines(node: DeriveBannerData['overview'] | undefined, depth = 0): string[] {
  if (node == null) return []
  const indent = '  '.repeat(Math.max(depth - 1, 0))
  const prefix = depth === 0 ? '' : '- '
  if (typeof node === 'string') {
    const text = node.trim()
    return text ? [`${indent}${prefix}${text}`] : []
  }
  const lines: string[] = []
  if (node.description && String(node.description).trim()) {
    lines.push(`${indent}${prefix}${String(node.description).trim()}`)
  }
  for (const child of node.items || []) {
    lines.push(...renderOverviewLines(child, depth + 1))
  }
  return lines
}

function wrapAsComment(body: string, style: DeriveBannerStyle): string {
  const normalizedBody = String(body).replace(/\r\n?/g, '\n')
  const escapedBody = style === 'block-star' || style === 'block-jsdoc'
    ? normalizedBody.replace(/\*\//g, '*\\/')
    : normalizedBody
  const lines = escapedBody.split('\n')
  if (style === 'line-slash') {
    return lines.map(line => `// ${line}`).join('\n')
  }
  if (style === 'line-hash') {
    return lines.map(line => `# ${line}`).join('\n')
  }
  if (style === 'block-star') {
    const content = lines.map(line => ` * ${line}`).join('\n')
    return `/*\n${content}\n */`
  }
  const content = lines.map(line => ` * ${line}`).join('\n')
  return `/**\n${content}\n */`
}

type BannerConfig = Exclude<DeriveBanner, false> & { disabled?: boolean }
function resolveBannerConfig(banners: (DeriveBanner | undefined)[]): BannerConfig {
  if (!Array.isArray(banners)) return { disabled: true }
  return banners.reduce<BannerConfig>((config, banner) => {
    if (banner === undefined) return config
    if (banner === false) return { ...config, disabled: true }
    return {
      ...config,
      ...banner,
      disabled: false,
      data: {
        ...((config as any).data || {}),
        ...(banner.data || {})
      }
    }
  }, { disabled: true })
}

function getBannerFormatter({
  formatter, 
  template: str
}: Pick<Exclude<DeriveBanner, false>, 'formatter' | 'template'>): NonNullable<Exclude<DeriveBanner, false>['formatter']> {
  if (typeof formatter === 'function') return formatter
  if (typeof str === 'string') return context => template(str)({ data: context.data })
  return context => {
    if (!Object.keys(context.data).length) return ''
    if (toTextArray((context.data as any)?.author).length === 0) return ''
    return template(DEFAULT_TEMPLATE, {
      imports: {
        formatAuthors: (author: any) => toTextArray(author).join(', '),
        formatSources: (source: any) => toTextArray(source).join('; '),
        formatOverview: (overview: DeriveBannerData['overview']) => renderOverviewLines(overview).join('\n')
      }
    })({ data: context.data })
  }
}

export function getBanner(
  banners: (DeriveBanner | undefined)[],
  {
    path,
    content
  }: {
    path: string
    content: string
  }
): string {
  const config = resolveBannerConfig(banners)
  if (config.disabled) return ''

  const style = config.style ?? DEFAULT_STYLE
  const context: DeriveBannerContext = { 
    path, 
    content, 
    data: config.data || {}, 
    style 
  }

  const formatter = getBannerFormatter({ 
    template: config.template,  
    formatter: config.formatter
  })

  const body = formatter(context).trim()
  if (!body.trim()) return ''
  return `${wrapAsComment(body, style)}\n\n`
}
