import type { DeriveBanner, DeriveBannerData, BannerOverviewNode, BannerRenderContext, DeriveBannerStyle } from '../types.js'

const DEFAULT_STYLE: DeriveBannerStyle = 'block-jsdoc'

function toTextArray(value: unknown): string[] {
  if (value == null) return []
  const arr = Array.isArray(value) ? value : [value]
  return arr
    .map(v => String(v).trim())
    .filter(Boolean)
}

function renderOverviewLines(node: BannerOverviewNode | undefined, depth = 0): string[] {
  if (node == null) return []
  const indent = '  '.repeat(Math.max(depth - 1, 0))
  const prefix = depth === 0 ? '' : '- '
  if (typeof node === 'string') {
    const text = node.trim()
    return text ? [`${indent}${prefix}${text}`] : []
  }
  const lines: string[] = []
  if (node.description && node.description.trim()) {
    lines.push(`${indent}${prefix}${node.description.trim()}`)
  }
  for (const child of node.items || []) {
    lines.push(...renderOverviewLines(child, depth + 1))
  }
  return lines
}

function resolveValueByPath(pathExpr: string, context: Record<string, unknown>): unknown {
  const key = pathExpr.trim()
  if (!key) return ''
  const keys = key.split('.')
  let current: unknown = context
  for (const segment of keys) {
    if (current == null || typeof current !== 'object' || !(segment in (current as Record<string, unknown>))) {
      return ''
    }
    current = (current as Record<string, unknown>)[segment]
  }
  return current ?? ''
}

function renderTemplate(template: string, context: Record<string, unknown>): string {
  return String(template).replace(/<%=\s*([^%]+?)\s*%>/g, (_, expr: string) => {
    const value = resolveValueByPath(expr, context)
    return typeof value === 'string' ? value : value == null ? '' : String(value)
  })
}

function buildDefaultBody(data: DeriveBannerData): string {
  const authors = toTextArray(data.author)
  if (!authors.length) return ''
  const sources = toTextArray(data.source)
  const overview = renderOverviewLines(data.overview as BannerOverviewNode | undefined)
  const authorText = authors.join(', ')
  const lines = [
    '@generated',
    `本文件由 ${authorText} 自动生成，请勿手动修改。`,
    `This file is automatically generated by ${authorText}. DO NOT EDIT BY HAND.`
  ]
  if (sources.length) {
    const sourceText = sources.join('; ')
    lines.push(`如需修改，请修改源文件：${sourceText}`)
    lines.push(`To make changes, please edit the source file: ${sourceText}`)
  }
  if (overview.length) {
    lines.push('')
    lines.push('@fileoverview')
    lines.push(...overview)
  }
  return lines.join('\n')
}

function wrapAsComment(body: string, style: DeriveBannerStyle): string {
  const normalizedBody = String(body).replace(/\r\n?/g, '\n')
  const escapedBody = style === 'block-star' || style === 'block-jsdoc'
    ? normalizedBody.replace(/\*\//g, '*\\/')
    : normalizedBody
  const lines = escapedBody.split('\n')
  if (style === 'line-slash') {
    return lines.map(line => `// ${line}`).join('\n')
  }
  if (style === 'line-hash') {
    return lines.map(line => `# ${line}`).join('\n')
  }
  if (style === 'block-star') {
    const content = lines.map(line => ` * ${line}`).join('\n')
    return `/*\n${content}\n */`
  }
  const content = lines.map(line => ` * ${line}`).join('\n')
  return `/**\n${content}\n */`
}

export function renderBannerForFile(
  banner: DeriveBanner | undefined,
  {
    path,
    content
  }: {
    path: string
    content: string
  }
): string {
  if (!banner) return ''
  const style = banner.style ?? DEFAULT_STYLE
  const data = (banner.data || {}) as DeriveBannerData
  const context: BannerRenderContext = { path, content, data, style }
  let body = ''
  if (banner.formatter) {
    body = String(banner.formatter(context) || '')
  } else if (banner.template) {
    body = renderTemplate(banner.template, { ...data, data, path, style })
  } else if (data.author != null) {
    body = buildDefaultBody(data)
  }
  if (!body.trim()) return ''
  return `${wrapAsComment(body, style)}\n\n`
}
